# SETTING FILE IDENT TOKENS
EACH_TK = 'each'
WAIT_TK = 'wait'
CONSUMER_TK = 'consumer'
CONNECTOR_REPLACE_TK = 'connector'
API_TK = 'api'
USER_TK = 'user'
PASSWORD_TK = 'password'
CONNECTOR_NAME_TK = 'connectorName'
DEFAULT_TK = 'default'
DEV_TK = 'dev'
URL_TK = 'url'
SQL_TK = 'sql'
LOCAL_ID_TK = 'localId'