active_executions: # names of executions to run when the execution starts
    - excel-dev
    - calonge-dev

executions:
  calonge-dev:
    type: database
    repeat_each_seconds: 5 # process executes every n seconds
    topic: buffering
    bootstrap_server: XXXXXXXXX:9094
    url: postgresql://calonge_inventory_u:v1gMNG1knv@XXXXXXXXX:5432/calonge
    sql: "select * from data.gbi_posiciones_vehiculos gpv limit 100;"

  excel-dev:
    type: ftp
    repeat_each_seconds: 5 # process executes every n seconds
    topic: excel-buffering
    bootstrap_server: XXXXXXXXX:9094
    file: data.xlsx
    user: fani
    password: 3icFWr9v
    host: XXXXXXXXX

